### ISSUE TITLE
Ring range extender power source not shared with home assistant

### ISSUE THREAD

**Issue by jatgm1** [jason0x43/hacs-hubitat#103]
So basically I am trying to use a ring range extender v1 which has "mains" and "battery" as the two states for power source and 0-100 percent as the "battery" state with home assistant. I tried unsharing and readadding and reloading the addon and restarting everything, even unplugging and replugging the repeater so the state changes then reloading. I want to use it as a power failure detector. Unfortunately only the "battery" state is seen by home assistant and not "power source" or of it is on mains or battery. So I cannot use it to detect power outage without a virtual device configured to do something upon state changes. Not the Biggest deal whatsoever, but would be super cool if it worked :)

**Comment by jatgm1** [comment]
Sku: "4ar1s70en0"
model name : "Ring Range Extender US"
Power input: "100-240v-50/60hz 30ma"

**Comment by jason0x43** [comment]
If possible, a copy of whatever you get from the Maker API for that device would be helpful. You can grab the data for it with `curl`, like:

```
$ curl http://<hubitat ip>/apps/api/<maker API id>/devices/<device id>?access_token=<maker API token>&prettyPrint=true
```

If that works, you should get something back like:

<details>
<pre>
{
    "id": "92",
    "name": "Aeotec Nano Switch",
    "label": "Back Yard Light",
    "attributes": [
        {
            "name": "powerLow",
            "currentValue": null,
            "dataType": "NUMBER"
        },
        {
            "name": "voltage",
            "currentValue": 0,
            "dataType": "NUMBER"
        },
        {
            "name": "energyTime",
            "currentValue": null,
            "dataType": "NUMBER"
        },
        {
            "name": "power",
            "currentValue": 0,
            "dataType": "NUMBER"
        },
        {
            "name": "energyDuration",
            "currentValue": null,
            "dataType": "STRING"
        },
        {
            "name": "powerHigh",
            "currentValue": null,
            "dataType": "NUMBER"
        },
        {
            "name": "current",
            "currentValue": null,
            "dataType": "NUMBER"
        },
        {
            "name": "switch",
            "currentValue": "on",
            "dataType": "ENUM",
            "values": [
                "on",
                "off"
            ]
        },
        {
            "name": "energy",
            "currentValue": 0,
            "dataType": "NUMBER"
        },
        {
            "name": "voltageHigh",
            "currentValue": null,
            "dataType": "NUMBER"
        },
        {
            "name": "currentHigh",
            "currentValue": null,
            "dataType": "NUMBER"
        },
        {
            "name": "currentLow",
            "currentValue": null,
            "dataType": "NUMBER"
        },
        {
            "name": "voltageLow",
            "currentValue": null,
            "dataType": "NUMBER"
        },
        {
            "name": "switch",
            "currentValue": "on",
            "dataType": "ENUM",
            "values": [
                "on",
                "off"
            ]
        }
    ],
    "capabilities": [
        "Configuration",
        "Actuator",
        "VoltageMeasurement",
        {
            "attributes": [
                {
                    "name": "voltage",
                    "dataType": null
                }
            ]
        },
        "Refresh",
        "PowerMeter",
        {
            "attributes": [
                {
                    "name": "power",
                    "dataType": null
                }
            ]
        },
        "EnergyMeter",
        {
            "attributes": [
                {
                    "name": "energy",
                    "dataType": null
                }
            ]
        },
        "Outlet",
        {
            "attributes": [
                {
                    "name": "switch",
                    "dataType": null
                }
            ]
        },
        "Switch",
        {
            "attributes": [
                {
                    "name": "switch",
                    "dataType": null
                }
            ]
        },
        "Sensor"
    ],
    "commands": [
        "reset",
        "refresh",
        "configure",
        "off",
        "on"
    ]
}
</pre>
</details>

**Comment by jatgm1** [comment]
Sorry but how would I find these values for the device? I think I've pretty much only used curl for installing a vpn on my pi 😅

**Comment by jason0x43** [comment]
The values other than the device ID are the same ones you used when adding the integration to HA (hub IP, maker API ID, maker API token). The device ID can be found by going to a device page in Hubitat and looking at the URL. For the device above (my "Back Yard Light"), the URL of the device page in Hubitat is `http://hubitat.local/device/edit/92`, and the device ID is `92`.

**Comment by jatgm1** [comment]
$ {"id":"243","name":"Z wave extender pwrmon","label":"Z wave pwrmon","attributes":[{"name":"battery","currentValue":100,"dataType":"NUMBER"},{"name":"powerSource","currentValue":"mains","dataType":"ENUM","values":["battery","dc","mains","unknown"]}],"capabilities":["Configuration","Actuator","PowerSource",{"attributes":[{"name":"powerSource","dataType":null}]},"Refresh","Battery",{"attributes":[{"name":"battery","dataType":null}]},"Sensor"],"commands":["refresh","configure"]}
 I got this,

 pardon the weird spacing I used TeamViewer to remote into the pi to issue the command and emailed it to myself then opened it on my phone and pasted it in

**Comment by jatgm1** [comment]
Current States
battery : 100
powerSource : mains
State Variables
initialized : true

This is what hubitat says.

**Comment by jason0x43** [comment]
Thanks, that's perfect. I'll try to add support for power source sensors in the next couple of days.

**Comment by jatgm1** [comment]
Awesome thank you :)

**Comment by jason0x43** [comment]
This should be supported in v0.6.3 (commit https://github.com/jason0x43/hacs-hubitat/commit/4fe7d052ad876ea581b5595b0ab1293e464266e6). Unfortunately I don't seem to have any devices with the PowerSource capability, so I haven't been able to test it (other than to see that nothing is broken 😁). Let me know if that version works. You should get `sensor.*_power_source` entities for any device with a PowerSource capability.

**Comment by jatgm1** [comment]
Wikid :) is the update available now? Jw 😅, have doesn't seem to have it on, also, unrelated matter, if one were to want to learn how to create integrations for the home assistant where would one start?

**Comment by jason0x43** [comment]
Ah, sorry, I pushed the update to GitHub bit didn't mark it as a release, so HACS wouldn't be able to see it. It should be available now.

As far as learning how to create integrations, Home Assistant has [some documentation](https://developers.home-assistant.io/docs/creating_component_index) for that. The docs are helpful for giving you a general idea of how an integration is structured and how it works, but I've found that looking through existing integrations, both the ones built into HA and external ones, to be the most helpful. They will give you the most up-to-date view of what an integration should look like; the docs sometimes lag when changes are made to APIs.

**Comment by jatgm1** [comment]
Cool :) thank you 😊

**Comment by jason0x43** [comment]
Any updates?

**Comment by jatgm1** [comment]
Oh ya sorry it works dandy :)

**Comment by jason0x43** [comment]
Great! 😄

**Comment by truvec** [comment]
I have the ring extenders and they are reporting great with one issue. If you set it as a power sensor it expects watts as a value. Since a power sensor is:
power: Power in W or kW.
power: on means power detected, off means no power

**Comment by truvec** [comment]
In HA this device is being set as a device_class_power. this sensor is for Power in W or kW.  Could this be changed to the default class or none? otherwise it works fine. Thanks
