### ISSUE TITLE
0.67 Not Working

### ISSUE THREAD

**Issue by BlueMoon23** [jason0x43/hacs-hubitat#121]
I upgraded to 0.67 last night and now nothing related to Hubitat works. I have restarted the HASS and tried updating the information. On the dashboard some buttons are showing as unavailable, while others don;t show unavailable, but once clicked, "Failed to call service" shows. All the devices appear to be showing on the configuration page. On the Entities Page, the status shows a red icon, as per the image below. Any ideas?

![image](https://user-images.githubusercontent.com/21972216/118236067-859d5080-b48d-11eb-8f18-5bbc043f8c55.png)

**Comment by jason0x43** [comment]
Could you check the logs? There may be an error in there that indicates what happened.

Also, what version did you update from?

**Comment by BlueMoon23** [comment]
Which logs do you want me to look at? I am fairly new to HA, although I have been running HE for a few years. There are a number of logs, the Logbookjust shows events for entities, while the Logs within the configuration page only shows today's activities, and this happened yesterday. I updated it a few weeks ago, so I believe it was from 0.66.

Regards

John

**Comment by BlueMoon23** [comment]
I have tried uninstalling the Hubitat Integration in order to re-install, but am running into difficulties. I have removed the integration from both HACS and Configuration. Added it via HACS, and then tried to add it as an integration, but keep getting the error: Config Flow could not be loaded. When I try adding it again, HASS freezes. Any ideas?

**Comment by jason0x43** [comment]
The log to look at is HA's system log, in `config/home-assistant.log`. How to view that log depends on how you've installed HA. If you're running HA on a Pi, you can setup the Terminal add-on and ssh into HA, or install the Samba add-on and browse to the config directory over the network. If you have HA running in a docker container, the log will be in whatever config directory is being mapped into the container.

The system log shows all the messages emitted by HA and its integrations since HA was last started. It's a good starting place when trying to track down why something isn't working.

**Comment by BlueMoon23** [comment]
It is only showing the log from today, as I had not enabled the Logger capability, as I said I am new to HASS. I have HASS running in Docker and I am currently rebooting my Server to see if this makes a difference. I'll probably end up removing then trying to re-install HASS in docker, but the time spent doing this may mean that I just go back to the HE dashboard if it happens again, it is slow, but it is more reliable.

**Comment by jason0x43** [comment]
Not having older logs is fine -- just restart HA (which it sounds like you're doing) and see what the log shows. If HA freezes, there should be something in there to indicate why, or if HE devices fail to work, there should be device or integration level errors.

**Comment by BlueMoon23** [comment]
Ok, thanks. this is what I am getting:  Error occurred loading configuration flow for integration hubitat: cannot import name 'COLOR_MODE_BRIGHTNESS' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py) Any thoughts?

**Comment by jason0x43** [comment]
Thanks, that helps! It looks like the latest update to the integration is trying to access a constant that isn't present in your version of HA. I'll add some backward compatibility code. Just out of curiosity, what version of HA are you running?

**Comment by BlueMoon23** [comment]
Looking in HASS I am on Home Assistant 2021.3.4, not sure if it is the latest, I am on a QNAP and is doesn't update automatically.

**Comment by BlueMoon23** [comment]
Also, I tried reinstalling V0.66 and go the same error.

**Comment by BlueMoon23** [comment]
Hi Jason,

Which logs do you want me to look at? I am fairly new to HA, although I
have been running HE for a few years. There are a number of logs, the Look
just shows events for entities, while the Logs within the configuration
page only shows today's activities, and this happened yesterday. I updated
it a few weeks ago, so I believe it was from 0.66.

Regards

John

**Comment by jason0x43** [comment]
This is fixed in v0.6.8. The problem was that the lighting update made in v0.6.7 used some constants that weren't included in HA until v2021.4.0 (the current version is 2021.5.4).

**Comment by BlueMoon23** [comment]
Thanks, that looks to have worked.
