### ISSUE TITLE
hubitat no longer loads past home assistant version core-2021.5.5

### ISSUE THREAD

**Issue by jatgm1** [jason0x43/hacs-hubitat#126]
hubitat doesnt load after core-2021.5.5. if i update it refuses to load. idk whats wrong but i need it to work for my whole smarthome lol.

**Comment by jason0x43** [comment]
Is this still an issue? I haven't run into an issues using the integration with HA 2021.6 and 2021.7.

**Comment by jason0x43** [comment]
Closing this since I've never been able to reproduce.
