### ISSUE TITLE
Device names are now incorrect

### ISSUE THREAD

**Issue by StephenJondrew** [jason0x43/hacs-hubitat#133]
Hello,

I noticed that recently many of my hubitat devices now have one of their properties added after the device name in Home Assistant. For example, 'temperature', 'power', 'last update time'. It appears that the devices have all of the correct properties within the device; however, the device names are just incorrect.

For example:

**Hubitat Device Name: ** Den Motion Sensor
**Home Assistant Device Name: ** Den Motion Sensor temperature
**Device Type:** SmartThings Motion Sensor

**Hubitat Device Name: ** Garage Yard Door
**Home Assistant Device Name: ** Garage Yard Door temperature
**Device Type:** Generic Zigbee contact sensor

**Hubitat Device Name: ** Den Button
**Home Assistant Device Name: ** Den Button temperature
**Device Type:** SmartThings button

**Hubitat Device Name: ** Front Lights
**Home Assistant Device Name: ** Front Lights power
**Device Type:** Inovelli Red Series Switch

**Hubitat Device Name: ** Entry Bench
**Home Assistant Device Name: ** Entry Bench last update time
**Device Type:** Wiz light bulb

**Comment by jason0x43** [comment]
I believe this is a result of some changes to how devices are being initialized.

**Comment by StephenJondrew** [comment]
If it helps, I've just noticed that the entities are also showing the incorrect name (for example sensor.front_lights_power)

**Comment by bmorgenthaler** [comment]
I just replaced two z-wave switches and updated everything and now most of my devices have "last updated time" tagged onto their names.

**Comment by bmorgenthaler** [comment]
I should also mention a lot of devices now have a disabled sensor entity i.e. sensor.kitchen_perimeter_can_lights_last_update_time. This is for a GE Enbrighten Z-Wave Switch

**Comment by jason0x43** [comment]
The `last_update_time` sensor was added a while back as a tool to help identify sensors that had stopped reporting. The fact that devices are ending up with that name is a recently introduced bug.
