### ISSUE TITLE
GE/Jasco 26931 Z-Wave motion switch - cannot set motion sensing mode

### ISSUE THREAD

**Issue by cgallred** [jason0x43/hacs-hubitat#141]
These in-wall motion-sensing switches can be sent a command to change the motion sensing mode. Would it be possible for hacs-hubitat to expose the mode-setting commands to HA so I can use them in e.g. Node-RED?

There are three modes: manual, vacancy, and occupancy. I have one installed in the upstairs hall bathroom. During the day I have it set to occupancy mode (auto-on, auto-off triggered by the motion sensor). At night I have it set to vacancy mode (manual on, auto-off) so that when one of the kids goes into the bathroom in the middle of the night they have the opportunity to close the door before potentially flooding the hallway with light, but it will at least still shut itself off if they forget to do it themselves.

When I was using webCoRE on HE I was able to create pistons that could send commands to change modes:
![image](https://user-images.githubusercontent.com/13487734/130121731-9dfb145d-bf8b-4226-b213-046821790708.png)

Unfortunately the mode commands are not exposed via hacs-hubitat so far as I can tell.

Here's the Maker API device info, showing that he commands are exposed. Please let me know if I can provide more info:
```json
{
    "id": "309",
    "name": "GE/Jasco Z-Wave Motion Switch",
    "label": "Upstairs Bathroom Light",
    "type": "GE Z-Wave Plus Motion Switch",
    "attributes": [
        {
            "name": "motion",
            "currentValue": "inactive",
            "dataType": "ENUM",
            "values": [
                "inactive",
                "active"
            ]
        },
        {
            "name": "pushed",
            "currentValue": null,
            "dataType": "NUMBER"
        },
        {
            "name": "numberOfButtons",
            "currentValue": null,
            "dataType": "NUMBER"
        },
        {
            "name": "switch",
            "currentValue": "off",
            "dataType": "ENUM",
            "values": [
                "on",
                "off"
            ]
        },
        {
            "name": "switch",
            "currentValue": "off",
            "dataType": "ENUM",
            "values": [
                "on",
                "off"
            ]
        }
    ],
    "capabilities": [
        "MotionSensor",
        {
            "attributes": [
                {
                    "name": "motion",
                    "dataType": null
                }
            ]
        },
        "Configuration",
        "Actuator",
        "Refresh",
        "Light",
        {
            "attributes": [
                {
                    "name": "switch",
                    "dataType": null
                }
            ]
        },
        "Switch",
        {
            "attributes": [
                {
                    "name": "switch",
                    "dataType": null
                }
            ]
        },
        "Sensor",
        "PushableButton",
        {
            "attributes": [
                {
                    "name": "numberOfButtons",
                    "dataType": null
                },
                {
                    "name": "pushed",
                    "dataType": null
                }
            ]
        }
    ],
    "commands": [
        "DebugLogging",
        "Manual",
        "Occupancy",
        "Vacancy",
        "configure",
        "off",
        "on",
        "push",
        "refresh",
        "setLightTimeout"
    ]
}
```

**Comment by jason0x43** [comment]
The integration generally only exposes commands associated with particular capabilities. However, it also provides a generic `hubitat.send_command` service that can be used to send arbitrary commands to a device. Try that, using one of the command names from the "commands" list and an entity that belongs to the device you want to send the command to.

<img width="834" alt="PNG image" src="https://user-images.githubusercontent.com/1042866/130140393-5508e075-b3d0-459f-b208-3fae1386e9ef.png">

**Comment by cgallred** [comment]
Thanks, that worked!
