### ISSUE TITLE
Requested Feature: sirens

### ISSUE THREAD

**Issue by jessegutkowski** [jason0x43/hacs-hubitat#142]
Thanks a million for this integration with Hubitat; it really makes moving to Home Assistant a breeze.

One feature that I would love is if you supported sirens (specifically the Aeotec Doorbell).  This is my last remaining "Rule Machine" rule.

**Comment by jason0x43** [comment]
Devices with the [alarm](https://docs.hubitat.com/index.php?title=Driver_Capability_List#Alarm) capability are supported. If you could send me the [Hubitat data](https://github.com/jason0x43/hacs-hubitat#checking-device-capabilities) for the device you're interested in, I can see what's involved in supporting it.

**Comment by jessegutkowski** [comment]
Thanks Jason.  Data is below.  Please let me know if I'm missing something.

{"id":"416","name":"Aeotec Siren 6 New","label":"Doorbell","type":"Aeotec Doorbell 6","attributes":[{"name":"mute","currentValue":"unmuted","dataType":"ENUM","values":["unmuted","muted"]},{"name":"switch","currentValue":null,"dataType":"ENUM","values":["on","off"]},{"name":"volume","currentValue":50,"dataType":"NUMBER"},{"name":"soundEffects","currentValue":"{\"0\":\"None\",\"1\":\"Ding Dong\",\"2\":\"Ding Dong Tubular Bell\",\"3\":\"Traditional Buzzer\",\"4\":\"Electric Buzzer\",\"5\":\"Westminster Chimes\",\"6\":\"Chimes\",\"7\":\"Cuckoo\",\"8\":\"Traditional Bell\",\"9\":\"Smoke Alarm (Low)\",\"10\":\"Smoke Alarm (High)\",\"11\":\"Fire Evacuation Buzzer\",\"12\":\"Carbon Monoxide Sensor\",\"13\":\"Klaxon\",\"14\":\"Klaxon (Deep)\",\"15\":\"Warning Tone\",\"16\":\"Tornado Siren\",\"17\":\"Alarm\",\"18\":\"Deep Alarm Tone\",\"19\":\"Alarm (Archangel tone)\",\"20\":\"Alarm (Shrill)\",\"21\":\"Digital Siren\",\"22\":\"Alert Series\",\"23\":\"Bell\",\"24\":\"Clock Buzzer\",\"25\":\"Christmas Tree\",\"26\":\"Gong\",\"27\":\"Single Bell Ting\",\"28\":\"Tonal Pulse\",\"29\":\"Upwards Tone\",\"30\":\"Door Open\"}","dataType":"JSON_OBJECT"},{"name":"soundName","currentValue":"None","dataType":"STRING"},{"name":"status","currentValue":"stopped","dataType":"ENUM","values":["playing","stopped"]}],"capabilities":["Configuration","Actuator","Refresh","Chime",{"attributes":[{"name":"soundEffects","dataType":null},{"name":"status","dataType":null},{"name":"soundName","dataType":null}]},"Tone","AudioVolume",{"attributes":[{"name":"volume","dataType":null},{"name":"mute","dataType":null}]},"Switch",{"attributes":[{"name":"switch","dataType":null}]}],"commands":["beep","configure","mute","off","on","pairButton1","pairButton2","pairButton3","playSound","refresh","setVolume","stop","unmute","volumeDown","volumeUp"]}
