### ISSUE TITLE
sensor.mode never updates?

### ISSUE THREAD

**Issue by PlinyElderATX** [jason0x43/hacs-hubitat#145]
I'm attempting to have some automations in HA alter based on the mode hubitat is in (Day, Evening, Night - in my case). I think I've potentially found a bug in that for some reason HA always seems to think the mode is "Day" I've tried manually changing it in addition to letting time pass for it to get to a new mode through mode manager... HA always seens it as Day. Specifically this is sensor.hub_mode. I can get the proper mode from hubitat in Node-Red if I use the nodes that connect to hubitat directly to query.

**Comment by jason0x43** [comment]
Yeah, it's kind of surprising. Events that don't come from devices, like HSM status and the hub's mode, count as "location" events.
