### ISSUE TITLE
Iris Button - No Event Emitters

### ISSUE THREAD

**Issue by SPCulhane** [jason0x43/hacs-hubitat#15]
Not a huge issue for me but I have been testing different kind of devices I have in my box of junk. One of the items is an Iris Button. Hubitat uses a built-in driver (Iris Button Controller). The Battery and Temp sensor are there in HA. When I try to create an automation, none of the button event emitters are displayed:
![image](https://user-images.githubusercontent.com/790943/75034754-e6e99600-547b-11ea-94a6-d40239d0224c.png)

Here is the error in log:
```
2020-02-21 07:29:09 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140344189711824] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 20, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 214, in websocket_device_automation_list_triggers
    triggers = await _async_get_device_automations(hass, "trigger", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 133, in _async_get_device_automations
    for domain in domains
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 107, in _async_get_device_automations_from_domain
    return await getattr(platform, function_name)(hass, device_id)
  File "/config/custom_components/hubitat/device_trigger.py", line 120, in async_get_triggers
    num_buttons = int(device.attributes[ATTR_NUM_BUTTONS].value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

I was able to manually create an automation and it works:
```
- id: '1582167576045'
  alias: test
  description: ''
  trigger:
  - device_id: 2772a3820de94966a0cde1f3809fe5f2
    domain: hubitat
    platform: device
    subtype: '1'
    type: pushed
  condition: []
  action:
  - entity_id: light.office
    service: light.toggle
```

The device in HE:
![image](https://user-images.githubusercontent.com/790943/75034974-61b2b100-547c-11ea-901c-2579353284c9.png)

HE Log when button is pressed:
```
app:5132020-02-21 07:35:29.675 am debugdevice event: {"name":"pushed","value":"1","displayName":"Iris Button","deviceId":"257","descriptionText":"Iris Button button 1 was pushed","unit":null,"data":null}
app:5132020-02-21 07:35:26.870 am debugdevice event: {"name":"pushed","value":"1","displayName":"Iris Button","deviceId":"257","descriptionText":"Iris Button button 1 was pushed","unit":null,"data":null}
```
HA Log when button is pressed:
```
2020-02-21 07:35:26 DEBUG (MainThread) [custom_components.hubitat.device] emitted event <Event device_id="257" device_name="Iris Button" attribute="pushed" value="1" description="Iris Button button 1 was pushed">
2020-02-21 07:35:29 DEBUG (MainThread) [custom_components.hubitat.device] emitted event <Event device_id="257" device_name="Iris Button" attribute="pushed" value="1" description="Iris Button button 1 was pushed">
```

Like I said before. Not a huge issue as I'm probably not going to use this button but wanted to bring it to your attention in case other report a similar issues with the same or other devices.

**Comment by jason0x43** [comment]
Hmmm...is it just a single button device?

If you get a chance, run this command from a command line (assuming you have `curl` available) and post the data you get:

`$ curl 'http://<your hubitat address>/apps/api/<maker API ID>/devices/<Iris device ID>'`

I'm curious to see what capabilities and attributes the device advertises. It doesn't look like it has a `numberOfButtons` attribute, which is a case I hadn't anticipated for a Hubitat pushbutton device.

**Comment by jason0x43** [comment]
Possibly this is related? https://community.hubitat.com/t/button-controller-bug-v3-only-with-iris-button-controller/18415/9?u=jason0x43

**Comment by SPCulhane** [comment]
hmm, it's a possibility it is related to that bug. It is only a single button device.

I grabbed this using a browser.
```
{"id":"257","name":"Iris Button Controller","label":"Iris Button","attributes":[{"name":"battery","currentValue":100,"dataType":"NUMBER"},{"name":"held","currentValue":1,"dataType":"NUMBER"},{"name":"numberOfButtons","currentValue":null,"dataType":"NUMBER"},{"name":"pushed","currentValue":1,"dataType":"NUMBER"},{"name":"temperature","currentValue":65.38,"dataType":"NUMBER"}],"capabilities":["TemperatureMeasurement",{"attributes":[{"name":"temperature","dataType":null}]},"Battery",{"attributes":[{"name":"battery","dataType":null}]},"Configuration","Refresh","Sensor","HoldableButton",{"attributes":[{"name":"held","dataType":null}]},"PushableButton",{"attributes":[{"name":"numberOfButtons","dataType":null},{"name":"pushed","dataType":null}]}],"commands":["configure","hold","push","refresh"]}
```

**Comment by jason0x43** [comment]
That does look like it's related to that bug. If you click "Save Preferences" on the device page, does a `numberOfButtons` state variable show up?

I'll also update the code to handle the case where `numberOfButtons` is null; it can just assume 1 button in that case.

**Comment by SPCulhane** [comment]
It sure is. When I clicked "Save Preferences", the state variable showed. Now I have the options within HA when I click on "Create Automation with Device"
