### ISSUE TITLE
Unable to change API Token

### ISSUE THREAD

**Issue by nckolas** [jason0x43/hacs-hubitat#153]
I accidentally reset my MakerAPI Token today, obviously, this broke HAs ability to call my Hubitat. When going into the Configuration of the Integration, I am only presented with 4 Fields to edit, none of with are the API Token. Is there not a way to edit the token after the initial setup?

**Comment by nckolas** [comment]
After looking through some other issues, it appears the best way to fix this is to delete the integration and re-install. I will take this approach.

**Comment by jason0x43** [comment]
Yup, deleting and reinstalling is the way to go. The API token is used to generate the unique IDs for all the devices and entities created by the integration, so even if it could be changed, all the devices would need to be removed and recreated.
