### ISSUE TITLE
Fail to add Hubitat integration - Unexpected Error

### ISSUE THREAD

**Issue by zuohaot** [jason0x43/hacs-hubitat#16]
Hello,

I really appreciate yout work. However, I am not able to add Hubitat currently. It keeps showing "Unexpected Error" when I was trying to input Hub IP, App ID and token.

When I was checking log, it showed this:
```
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hubitat/config_flow.py", line 71, in async_step_user
    info = await validate_input(user_input)
  File "/config/custom_components/hubitat/config_flow.py", line 43, in validate_input
    hub = Hub(data[CONF_HOST], data[CONF_APP_ID], data[CONF_ACCESS_TOKEN])
  File "/config/custom_components/hubitat/device.py", line 55, in __init__
    if not CONF_HOST in entry.data:
AttributeError: 'str' object has no attribute 'data'
```

Could you tell me what I should do? Thank you

**Comment by zuohaot** [comment]
I am running Hass.io on Synology Docker.
Supervisor ver.: 201
Hubitat ver.: 0.4.5
HA ver.: 0.105.5

**Comment by jason0x43** [comment]
This is a bug caused by a recent refactor. I should have a fix out relatively soon.
