### ISSUE TITLE
Https support for event listener server

### ISSUE THREAD

**Issue by kevdliu** [jason0x43/hacs-hubitat#160]
Opened some PRs to add https support to the event listener server, hoping you can take a look when you get a chance. 

https://github.com/jason0x43/hacs-hubitat/pull/158

https://github.com/jason0x43/hubitatmaker/pull/16

Been running them locally for a while now with no issues. 

Thank you!

**Comment by jason0x43** [comment]
Thanks for contributing! Sorry for not responding sooner -- I saw that these existed, and they sound like a good idea, I just haven't had a chance to take a look yet. Soon...

**Comment by kevdliu** [comment]
Ah OK, no worries! I wasn't sure if GitHub sends notifications for new PRs so just wanted to make sure you were aware of them. Thanks for creating this amazing integration btw I can't believe it's not official
