### ISSUE TITLE
Home Assistant Supervisor Does not have Hubitat under Integrations

### ISSUE THREAD

**Issue by Bboy486** [jason0x43/hacs-hubitat#162]
Might be a basic issue but I am not able to find Hubitat in HA Supervisor.

**Comment by Bboy486** [comment]
Yes. As mentioned the Hubitat integration does not show when looking under add-ons.

**Comment by jason0x43** [comment]
That's why I mentioned the readme -- the "Add-ons" button isn't part of the process. 🙂 

This is an "integration" rather than an "add-on". Although they sound similar, they're actually very different things. To install integrations, you'll need to either install the integration manually in your HA config folder, or you'll need to install HACS and use that to install the integration. I recommend HACS as that gives you easy access to a wide range of integrations.

**Comment by Bboy486** [comment]
I see. So I'm running HA supervisor. I think (new to HA) where I am not able to follow is that I am running HA supervisor in docker on a rpi4. My folder is called hass and within the folder I have a folder called blueprints, deps, and tts. The yaml files are in the root. 

Do I create a custom_components folder and copy the Hubitat and _init_.py folder in there? Do I need to restart the service after?

**Comment by jason0x43** [comment]
Yup, if you want to manually install the integration, that's the general process -- have a `custom_components` folder in your HA config folder, and copy this repo's `custom_components/hubitat` into your `custom_components` (you don't need the `custom_components/init.py`), then restart HA. At that point you should be able to add this integration from the Devices & Services page.

**Comment by Bboy486** [comment]
That is what I did but the integration does not show in HA. 
Configuration > Integration > +Add Integration (hubitat is not showing up)

**Comment by jason0x43** [comment]
Hmm…ok. On thing that has helped some people is, oddly enough, to clear your browser cache (or at least the cache related to your HA server), refresh the page, and check again.  Apparently the list of integrations doesn’t always update itself properly in the browser.

**Comment by Bboy486** [comment]
I tried that. Still nothing.

**Comment by jason0x43** [comment]
Do you see any relevant looking messages in the HA log (`config/home-assistant.log`)? You should at least see one like:

```
2022-03-14 09:39:10 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hubitat which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by Bboy486** [comment]
I do not

**Comment by jason0x43** [comment]
Hmmm...that implies that HA isn't seeing your `custom_components` directory for some reason. Your config folder structure should look something like:

```
config/
  blueprints/
  deps/
  tts/
  custom_components/
    hubitat/
      __init__.py
      alarm_control_panel.py
      binary_sensor.py
      ...
  home-assistant.log
  home-assistant_v2.db
  ...
```

**Comment by Bboy486** [comment]
<img width="282" alt="Screenshot_9" src="https://user-images.githubusercontent.com/16495657/158290804-44e06874-283d-4ddf-b092-65bb7592e474.png">

**Comment by jason0x43** [comment]
You don't need to add anything to `configuration.yaml`, just add the component to the `custom_components/` directory and restart HA, and HA should make the integration available. The fact that your log isn't showing a message about finding a custom integration makes it look like HA isn't seeing your `custom_components/` folder.

Presumably your `hassio` folder looks like?
```
hassio/
  deps/
  blueprints/
  home-assistant.log
  custom_components/
  ...
```

**Comment by jason0x43** [comment]
You posted just the `custom_components` folder. Given that HA doesn't seem to be seeing your `custom_components` folder (you said the log didn't show a message about finding the integration), I was wondering if the `custom_components` folder was in the proper location.

**Comment by Bboy486** [comment]
I was able to fix this by starting from scratch. Thank you for the troubleshooting
