### ISSUE TITLE
integration is failing upon installation

### ISSUE THREAD

**Issue by octvrium** [jason0x43/hacs-hubitat#178]
Integration is providing the error: Failing to set up and following logs are being generated:

Logger: homeassistant.config_entries
Source: custom_components/hubitat/hub.py:250 
Integration: Hubitat ([documentation](https://github.com/jason0x43/hacs-hubitat), [issues](https://github.com/jason0x43/hacs-hubitat/issues)) 
First occurred: 1:49:31 PM (1 occurrences) 
Last logged: 1:49:31 PM

Error setting up entry Hubitat (4e51d77f) for hubitat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hubitat/__init__.py", line 37, in async_setup_entry
    if not await hub.async_setup():
  File "/config/custom_components/hubitat/hub.py", line 250, in async_setup
    await self._hub.start()
  File "/usr/local/lib/python3.10/site-packages/hubitatmaker/hub.py", line 190, in start
    await self.load_devices()
  File "/usr/local/lib/python3.10/site-packages/hubitatmaker/hub.py", line 175, in load_devices
    await self._load_device(dev["id"], force_refresh)
  File "/usr/local/lib/python3.10/site-packages/hubitatmaker/hub.py", line 371, in _load_device
    json = await self._api_request(f"devices/{device_id}")
  File "/usr/local/lib/python3.10/site-packages/hubitatmaker/hub.py", line 420, in _api_request
    raise RequestError(resp)
hubitatmaker.error.RequestError: GET http://

**Comment by jason0x43** [comment]
It looks like the integration is having problems communicating with your hub.

The first step is to ensure that the correct values are being used when setting up the integration. The setup form looks like this:

<img width="576" alt="Screen Shot 2022-08-10 at 2 10 24 PM" src="https://user-images.githubusercontent.com/1042866/183985890-4489a2bd-7e5e-4499-8876-cca2cd8433ef.png">

The hub address should be the IP of your hub, like 10.0.1.23.

The app ID should be a number, like 1 or 5.

The access token should be a 36 character string, like `1ab2345c-123a-1a23-a123-a1b23456789c`.

You should be able to access a URL for one of your devices using these values, like:

```
http://10.0.1.23/apps/api/1/devices/55?access_token=1ab2345c-123a-1a23-a123-a1b23456789c
       \       /          |         \/
      hub address      app ID    device ID
```

Also note that this address must be accessible from your HA instance. That means your HA instance should be on the same network as your Hubitat hub, or you'll need to setup a route from HA to your Hubitat.

**Comment by octvrium** [comment]
It’s really weird because they are wired to the same internet router and I’m connected to Hubitat hub through mi laptop that is connected to a mesh network that exits from the very same lan.

This is how my HA integration and HE make api looks like:

[image0.png][image2.jpeg][image3.jpeg][image4.jpeg]

From Hubitat side, is anything off that should needed to be changed?

Thanks,


On Aug 10, 2022, at 2:18 PM, Jason Cheatham ***@***.***> wrote:

﻿

It looks like the integration is having problems communicating with your hub.

The first step is to ensure that the correct values are being used when setting up the integration. The setup form looks like this:

[Screen Shot 2022-08-10 at 2 10 24 PM]<https://user-images.githubusercontent.com/1042866/183985890-4489a2bd-7e5e-4499-8876-cca2cd8433ef.png>

The hub address should be the IP of your hub, like 10.0.1.23.

The app ID should be a number, like 1 or 5.

The access token should be a 36 character string, like 1ab2345c-123a-1a23-a123-a1b23456789c.

You should be able to access a URL for one of your devices using these values, like:

http://10.0.1.23/apps/api/1/devices/55?access_token=1ab2345c-123a-1a23-a123-a1b23456789c
       \       /          |         \/
      hub address      app ID    device ID


Also note that this address must be accessible from your HA instance. That means your HA instance should be on the same network as your Hubitat hub, or you'll need to setup a route from HA to your Hubitat.

**Comment by jason0x43** [comment]
>This is how my HA integration and HE make api looks like:
>
> [image0.png][image2.jpeg][image3.jpeg][image4.jpeg]

It looks like the images didn't attach.

**Comment by octvrium** [comment]
Here are the images.

![D872D1C7-2A7A-4420-8FC5-3B3D684ED4DB](https://user-images.githubusercontent.com/54385345/184019966-eccadcb6-43a1-41ca-84ab-eabd722a7216.png)
![71E91D23-5002-4E6E-911D-D1F1CB21A519](https://user-images.githubusercontent.com/54385345/184019971-9448ee99-c4c8-4ce0-afaa-bb07465f8aef.png)
![4F9190B4-C6E2-4587-A0A5-5F80E6C1908C](https://user-images.githubusercontent.com/54385345/184019975-c2e6eee7-38dd-44e1-98f7-c51b0c5de622.png)
![C32BD1BC-1150-4C47-BEBE-D1398F828433](https://user-images.githubusercontent.com/54385345/184019977-2ec9bd54-c939-4ce5-9b94-63e80c2e5a85.png)

**Comment by jason0x43** [comment]
Hmmm...all of that looks fine. Could you verify that the access token is correct (no extra spaces or anything)?

**Comment by octvrium** [comment]
I checked and seems fine. Also fresh installed HA (that workers in the past) and didn’t work either.


On Aug 21, 2022, at 10:01 AM, Jason Cheatham ***@***.***> wrote:

﻿

Hmmm...all of that looks fine. Could you verify that the access token is correct (no extra spaces or anything)?

**Comment by jason0x43** [comment]
It's been a while -- did you ever make any progress here?

**Comment by jason0x43** [comment]
I’m closing this since there hasn’t been an update in a while. Feel free to re-open if there’s still an issue.
