### ISSUE TITLE
Can not add integration

### ISSUE THREAD

**Issue by Dann0530** [jason0x43/hacs-hubitat#184]
When I try to add the integration, I get an error

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

How do I fix?

**Comment by jason0x43** [comment]
Questions:

* Where are you seeing the error? In the Home Assistant UI?
* What version of HA are you running?
* What version of the integration are you using?

**Comment by Dann0530** [comment]
I am running Home Assistant v22.10.4 in a virtual machine on proxmox v7.2-11. I loaded the Hubitat integration v0.8.1 through hacs v1.28.2. This error occurs in the HA UI.

Sent from Yahoo Mail on Android 
 
  On Tue., 18 Oct. 2022 at 7:09 p.m., Jason ***@***.***> wrote:   


Questions:
   
   - Where are you seeing the error? In the Home Assistant UI?
   - What version of HA are you running?
   - What version of the integration are you using?

**Comment by Dann0530** [comment]
I turned on logging and this is the error I got.

2022-10-19 15:46:10.719 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration hubitat: cannot import name 'ATTR_ALARM' from 'hubitatmaker.const' (/usr/local/lib/python3.10/site-packages/hubitatmaker/const.py)

**Comment by jason0x43** [comment]
What does your `/usr/local/lib/python3.10/site-packages/hubitatmaker/const.py` file look like? It should contain a large number of constants, including ATTR_ALARM.

**Comment by Dann0530** [comment]
I don't have a /usr/local/lib/python3.10 folder. The files are located in /usr/lib/python3.10.  there is no hubitatmaker folder in the site-packages folder.

**Comment by jason0x43** [comment]
Home Assistant manages integration dependencies (like hubitatmaker), but possibly HA didn't install the dependency in this case. You could try manually installing it (`pip install hubitatmaker`) and see if that works.

**Comment by Dann0530** [comment]
There was an update to HACS. After I updated, I redownloaded your integration. The installation was completed successfully.  I can  only assume that there was a problem with either HACS or HA. I can no longer troubleshoot this as everything is OK. Thanks for your help. You can close this issue.

**Comment by jason0x43** [comment]
Glad to hear things are working, and thanks for the update
