### ISSUE TITLE
Hub Mode does not change

### ISSUE THREAD

**Issue by mikea7531** [jason0x43/hacs-hubitat#189]
When changing mode using the select.hub_mode entity, it will change the mode in Hubitat, but does not show the correct current mode the hub is in. Once changed, I can't change back to the previous mode as HA already thinks it's in this mode. Also, sensor.hub_mode displays the incorrect hub mode. 

Even changing the hub mode directly in Hubitat, the hub mode is not reported correctly in HA. 

Please note, I am not using the standard hub mode names, I am using the following custom hub modes that I defined in my Hubitat Hub:

Normal
Away / Vacation
System Cutout
Enhanced System Cutout (Stops Timers)
Pre-Normal

![image](https://user-images.githubusercontent.com/116002615/207438418-17981b6a-290d-41af-9030-a85a16f0d115.png)

**Comment by mikea7531** [comment]
Disregard, didn't have a setting in Maker API checked. Keep up the good work!

**Comment by rywalters** [comment]
I'm having a similar problem. HA will not change the Hubitat hub mode; HA will not update its display of the hub mode and HE will not change modes. I have the Maker API set to allow control of modes.
