### ISSUE TITLE
Had to recreate maker api

### ISSUE THREAD

**Issue by Bboy486** [jason0x43/hacs-hubitat#192]
Is there somewhere where I can update the API in HACS if I have a new maker api access token? I don't see a way to update the API key in the configuration options. I would prefer to not have to recreate all of my entities/ dashboards if possible.

**Comment by jason0x43** [comment]
It’s possible, but a bit of a pain. #181 would address the issue.

You would need to:

1. Shut down HA
2. Edit config/.storage/core.config_entries
3. Find the Hubitat entry and note the first part of the current access token
4. Replace the access token with the new one
5. Edit config/.storage/core.device_registry
6. Replace all occurrences of the first part of the old access token with the first part of the new access token
7. Start HA

**Comment by Bboy486** [comment]
Any way to add this under advanced in the integration config (ability to update API)?

**Comment by jason0x43** [comment]
That's the eventual plan.
