### ISSUE TITLE
Error Updating Hubitat Integration in HACS

### ISSUE THREAD

**Issue by blucier69** [jason0x43/hacs-hubitat#199]
There was an update for the Hubitat integration shown in HACS (0.8.5 to 0.8.6) and upon updating it as I've done many times before, when clicking on the Update button, I just get the spinning circle and after a minute it comes back and still shows it needs to be updated.

When looking in the HACS logs, I see the following. about not being able to reach 
https://raw.githubusercontent.com/jason0x43/hacs-hubitat/v0.8.6/custom_components/hubitat/__init__.py.  I've confirmed I can reach that URL...

Duplicate log entries omitted...

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:721
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 7:05:29 PM (14 occurrences)
Last logged: 7:07:33 PM

A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/jason0x43/hacs-hubitat/v0.8.6/custom_components/hubitat/__init__.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 3
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/jason0x43/hacs-hubitat/v0.8.6/custom_components/hubitat/alarm_control_panel.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 2

Upon trying to restart HA (latest version 2023.3.1) the Hubitat integration fails to load and still shows Update Pending in HACS.

Is this possibly a HACS issue that needs to be discussed with that group or possibly an issue with the integration stuck in a partial upgraded status?

Uninstall Hubitat integration and re-load?  Hubitat hub is at latest version and I have rebooted it as well and all devices function from Hubitat natively.

Any ideas?

Adding anohter log entry after another HA reboot...
Logger: homeassistant.setup
Source: setup.py:213
First occurred: 7:36:24 PM (1 occurrences)
Last logged: 7:36:24 PM

Setup failed for custom integration hubitat: Unable to import component: No module named 'custom_components.hubitat.alarm_control_panel'

**Comment by jason0x43** [comment]
Hmmm…that’s a new one. I would suggest waiting a little while and trying to update again. It sounds like it may just be a temporary issue with GitHub.

**Comment by jason0x43** [comment]
Did this end up resolving itself?

**Comment by jason0x43** [comment]
I'm going to close this as it seems like a transient GitHub-related issue rather than something with this integration. Feel free to reopen the issue if the problem occurs again.
