### ISSUE TITLE
Way more Lights showing as Switches by default

### ISSUE THREAD

**Issue by jhstroebel** [jason0x43/hacs-hubitat#210]
After the recent update, everything that was natively coming over as a Light (smart switches with Light in the name mostly) is now coming over as a switch and the light entity is unavailable.  This is breaking automations and dashboards...

This is made worse by my last comment on the naming issues... The name for modifying these in the configuration is still the 'name' value rather than the 'label' we are correctly seeing elsewhere.  So I can't pinpoint which "Zooz ZEN Switch Advanced" or "Inovelli Dimmer..." is the one I'm trying to convert in config...

Possible this is related?  Maybe you were looking for "light" before in the old name (label), but its now looking at the 'name' field for this and not autodetecting?

**Comment by jason0x43** [comment]
This should be fixed in v0.9.3+.

**Comment by jhstroebel** [comment]
This did it!  Solved both problems.

Thank you again for the quick resolutions the last few days!
