### ISSUE TITLE
Duplicate entities created for door openers

### ISSUE THREAD

**Issue by mbaran5** [jason0x43/hacs-hubitat#22]
Not seeing any functional issues, but my two cover (Garage Door, Gate) trigger this every time I restart HA. 

`Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: cover.garage_door. Platform hubitat does not generate unique IDs`

Here's each devices capabilities
`[{"capabilities":["Switch",{"attributes":[{"name":"switch","currentValue":"off","dataType":"ENUM","values":["on","off"]}]},"ContactSensor",{"attributes":[{"name":"contact","currentValue":"closed","dataType":"ENUM","values":["closed","open"]}]},"Polling","Configuration","Refresh","Momentary","Sensor","Actuator","RelaySwitch",{"attributes":[{"name":"switch","currentValue":"off","dataType":"ENUM","values":["on","off"]}]},"DoorControl",{"attributes":[{"name":"door","currentValue":"closed","dataType":"ENUM","values":["unknown","closed","open","closing","opening"]}]},"GarageDoorControl",{"attributes":[{"name":"door","currentValue":"closed","dataType":"ENUM","values":["unknown","closed","open","closing","opening"]}]},"HealthCheck",{"attributes":[{"name":"checkInterval","currentValue":null,"dataType":"NUMBER","values":null}]}]}]`

`[{"capabilities":["ContactSensor",{"attributes":[{"name":"contact","currentValue":"open","dataType":"ENUM","values":["closed","open"]}]},"Sensor","Actuator","DoorControl",{"attributes":[{"name":"door","currentValue":"open","dataType":"ENUM","values":["unknown","open","closing","closed","opening"]}]},"GarageDoorControl",{"attributes":[{"name":"door","currentValue":"open","dataType":"ENUM","values":["unknown","open","closing","closed","opening"]}]}]}]`

**Comment by jason0x43** [comment]
Ah, I didn't expect a device to implement both GarageDoorControl and DoorControl, so entities are being double-created for those.

**Comment by mbaran5** [comment]
It might even be beneficial to skip them? I think only the garagedoorcontrol is needed, though I am not sure the functional difference... I know I don't need both entities.

**Comment by jason0x43** [comment]
Yeah, I just need to check for either capability instead of both separately.
