### ISSUE TITLE
Additional instructions for adding new devices

### ISSUE THREAD

**Issue by cableghost** [jason0x43/hacs-hubitat#223]
It took me forever to add a new device. I restarted HA, reloaded the integration, readded devices and then figured out I must first refresh the Maker list in Hubitat GUI and select them. Unless I missed it in the 'Adding New Devices' section, would you please add this.

**Comment by jason0x43** [comment]
The [Adding new devices](https://github.com/jason0x43/hacs-hubitat#adding-new-devices) section starts with "After adding new devices to the Maker API instance in Hubitat", but I agree that some more step-by-step instructions couldn't hurt. I'll update the readme.

**Comment by cableghost** [comment]
After reading that section again, I guess I just missed it, or interpreted it wrong... my bad.

**Comment by jason0x43** [comment]
I added some clearer setup instructions in 0e6ca91.
