### ISSUE TITLE
Default sensor Icons lost between 0.9.8 and 0.9.11

### ISSUE THREAD

**Issue by doctorkb** [jason0x43/hacs-hubitat#233]
Noticed with humditiy, CO2 and Illuminance sensors.

Had icons defaulted correctly in 0.9.8 (water drop percent, "CO2" and an open sun, respectively).  Upgrade to 0.9.11 changed all to eyes.

Downgraded to 0.9.8, issue resolved.

**Comment by jason0x43** [comment]
I believe this was because a regression caused sensors to stop reporting device classes in v0.9.11. This is fixed in v0.9.12. Give that try.

**Comment by doctorkb** [comment]
Appears to be resolved now!

Thanks!
