### ISSUE TITLE
Removed Entities Persist in HA and Cannot be Deleted

### ISSUE THREAD

**Issue by jianyu-li** [jason0x43/hacs-hubitat#236]
I had a virtual lock shared to Home Assistant. I removed the lock from Maker API and it says unavailable in Home Assistant but Home Assistant won't let me delete the entity![image](https://github.com/jason0x43/hacs-hubitat/assets/52750081/869992d1-a884-47e5-9f01-c207d802d6ac)

**Comment by jason0x43** [comment]
You can delete devices by going to the integrations panel in Home Assistant, opening Hubitat, and clicking the "Configure" button. Devices may be removed during the configuration process.

**Comment by jianyu-li** [comment]
wow I've never seen that before! Thank you!

**Comment by jianyu-li** [comment]
> You can delete devices by going to the integrations panel in Home Assistant, opening Hubitat, and clicking the "Configure" button. Devices may be removed during the configuration process.

Quick question: is it better to remove from maker API first then remove through the configure option or can you skip the Maker API part and just remove through the configure option?

**Comment by jason0x43** [comment]
You should remove them from the Maker API first, and then in the integration. Otherwise, they'll be added back the next time you restart HA.

I should probably just have the integration automatically remove devices that aren't exposed by the Maker API. 🙂
