### ISSUE TITLE
Color bulbs stopped working in 0.9.16

### ISSUE THREAD

**Issue by scheeni** [jason0x43/hacs-hubitat#238]
I was on version 0.9.8 and upgraded to version 0.9.16 via HACS. After the upgrade my bulbs would only turn on or off. All the color information was gone. When I looked at the attributes of the color bulb in Home Assistant I saw color_mode = "RGB" (instead of color_mode = "hs") and attributes such as rgb_color were null. This is for color bulbs that allow setting both color temperature and RGB  values. 

I downgraded to 0.9.8 manually and everything is back to the way it was (attributes from 0.9.8 reproduced below):

  > data: object
  > entity_id: "light.guest_hallway_color_bulbs"
  > state: true
  > attributes: object
  > min_color_temp_kelvin: 2000
  > max_color_temp_kelvin: 6535
  > min_mireds: 153
  > max_mireds: 500
  > supported_color_modes: array[2]
  > 0: "color_temp"
  > 1: "hs"
  > color_mode: "hs"
  > brightness: 38
  > color_temp_kelvin: null
  > color_temp: null
  > hs_color: array[2]
  > 0: 0
  > 1: 97
  > rgb_color: array[3]
  > 0: 255
  > 1: 7
  > 2: 7
  > xy_color: array[2]
  > friendly_name: "Guest Hallway Color Bulbs"
  > supported_features: 19
  > last_changed: "2024-01-02T06:07:44.484900+00:00"

**Comment by jason0x43** [comment]
I believe the issue was with how bulb color modes were being reported. They were returning `ColorMode.RGB` instead of `ColorMode.HS`. This is fixed in v0.9.17.

**Comment by scheeni** [comment]
I can confirm that color bulbs work again. Thank you!
