### ISSUE TITLE
Hubitat not loaded

### ISSUE THREAD

**Issue by michaelacosta-rpi** [jason0x43/hacs-hubitat#248]
After updating to the most recent:

Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.4

Hubitat says "not loaded" and I don't have the option to manually reload it. All of my sensors and switches are unavailable. I also tried to add an entry to hubitat as I've updated network equipment (maybe a different IP than it was before), but when I do that I get an error: Config flow could not be loaded: {"message":"Invalid handler specified"}.

I've restarted everything except the entire VM running it. Prior to this, it's been running fine for over a year with no issues.

**Comment by jason0x43** [comment]
Are you running the most recent version of the integration?

**Comment by michaelacosta-rpi** [comment]
I believe so, there's no update listed. I just restarted the VM though so I can't check right this second.

**Comment by jason0x43** [comment]
Hmmm...as far as I'm aware, the only reason that Hubitat wouldn't load is if you were running an older version (0.9.8 or before). Some deprecated code was finally removed in Home Assistant 2024.1.1 that broke the integration.

**Comment by jason0x43** [comment]
> How can I check the integration version?

How did you install the integration? If it was through HACS, HACS should show you what's installed. If you installed manually, the version is in the `manifest.json` file in the repo.

**Comment by michaelacosta-rpi** [comment]
I thought I installed through HACS, but it was a while ago and HACS doesn't have it listed. I just downloaded via HACS and am restarting. Makes sense if I had an outdated version.

**Comment by michaelacosta-rpi** [comment]
I downloaded via HACS, didn't do anything else, and the integration is working again. I assume it just updated when I downloaded the new version. Sorry to bug you but thank you so much for the immediate help!

**Comment by jason0x43** [comment]
No problem, and I'm glad it's working again!
