### ISSUE TITLE
Home Assistant Core Log Warning 

### ISSUE THREAD

**Issue by cuchipandy** [jason0x43/hacs-hubitat#255]
I'm using  ZWave MCO-MH8-FC Thermostats and logger is throwing that warning every boot.
It happens too with climate entities on Haier hOn integration.

"Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climatización ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 11:28:33 (10 occurrences)
Last logged: 11:30:20

Entity None (<class 'custom_components.hubitat.climate.HubitatThermostat'>) implements HVACMode(s): auto, heat, heat_cool, cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/jason0x43/hacs-hubitat/issues"

**Comment by jason0x43** [comment]
This has been resolved in v0.9.23.
