### ISSUE TITLE
Enhancement Request: Create a service to return the lock codes for a lock

### ISSUE THREAD

**Issue by irvintim** [jason0x43/hacs-hubitat#259]
Currently, the door locks have the codes removed from the list of codes in the  attribute, this request is to create a service that will get those codes and return them

**To Reproduce**

<!-- Steps to reproduce the behavior:
1. Go to 'Overview'
2. Click on 'One of the door locsk'
3. Scroll down to 'Attributes' and open
4. See a list of door codes, but the actual code is not shwon in the list, just the Name and postiion number.

**Screenshots**

**Environment**

 - Home Assistant version: 2024.2.1
 - Integration version: 0.9.22

** Fix **
The PR: https://github.com/jason0x43/hacs-hubitat/pull/258 contains a fix to this enhancement request

**Comment by irvintim** [comment]
I'm not sure where the rest of the text above went (I must have not closed a comment).  Anyway, long story short, I submitted PR https://github.com/jason0x43/hacs-hubitat/pull/258 to add this feature to the module.

**Comment by jason0x43** [comment]
Your PR has been merged and is in v0.9.23. Thanks for the contribution!

**Comment by irvintim** [comment]
Thanks!
