### ISSUE TITLE
Only service Available get_codes

### ISSUE THREAD

**Issue by magaman** [jason0x43/hacs-hubitat#270]
I'm no longer seeing any of the other services with the integration. Such as send command, the only option is hubitat.get_codes

**To Reproduce**

Go to dev tools and search in services.

**Environment**

 - Home Assistant version: 2024.3.3
 - Integration version: v0.9.26

**Comment by jason0x43** [comment]
Hmmm...I'm unable to reproduce the issue. With HA 2024.3.3 and integration v0.9.26, I see 9 services in dev tools.

<img width="772" alt="Screenshot 2024-03-30 at 20 13 58" src="https://github.com/jason0x43/hacs-hubitat/assets/1042866/b0b17718-64e9-458a-861c-96e6afe9fb82">

Have you tried refreshing the browser or reloading your HA app?

**Comment by magaman** [comment]
Fixed. I thought I reloaded….. seems this popped up when I removed a second hub from the integration
