### ISSUE TITLE
Delete unused devices 

### ISSUE THREAD

**Issue by danfox52** [jason0x43/hacs-hubitat#277]
When I delete a Hubitat device, (or just don't want it in HA) how do I delete it from HA? I know I can disable it, but it's there a way to delete it?

**Comment by danfox52** [comment]
Ah, I found it. Run configuration again.

**Comment by jason0x43** [comment]
I added a section to the README about [removing devices](https://github.com/jason0x43/hacs-hubitat?tab=readme-ov-file#removing-devices).
