### ISSUE TITLE
Request to support ‘transitions’ for Lights added via Hubitat. 

### ISSUE THREAD

**Issue by njguyuk891** [jason0x43/hacs-hubitat#287]
Hi

Could you consider adding support for transitions effects in automation Actions Turn Lights on.  (used to be called call service )
When adding a light added via Hubitat the transitions effects are missing. 

Thanks

**Comment by jason0x43** [comment]
v0.9.36 adds support for transitions, at least last much as the Maker API appears to support them, which is only for brightness and color temperature changes (not for color changes).

**Comment by njguyuk891** [comment]
Hi Thanks for that, can now see transitions in light actions.
