### ISSUE TITLE
HA Core 2024.10.1 - Hue temperature sensors not updating

### ISSUE THREAD

**Issue by rydercowan** [jason0x43/hacs-hubitat#290]
**Describe the bug**
Hue temperature sensors not updating in HA

After updating to HA Core 2024.10.1 temperatures no longer updating in HA
**To Reproduce**
Update to HA Core 2024.10.1.
Rolling back the update fixes the problem.

**Screenshots**

**Environment**

 - Home Assistant version:  2024.10.1
 - Integration version:  0.9.36

**Comment by jason0x43** [comment]
Are your Hue sensors coming from Hubitat?

**Comment by rydercowan** [comment]
After updating to 2024.10.2 the problem appears to be solved.
