### ISSUE TITLE
issue with event URL

### ISSUE THREAD

**Issue by dave2503** [jason0x43/hacs-hubitat#292]
Hi I have read alot of forums but I am having issues with event URL config. As read I have published the port 8122 in docker and set the event use HTTP://ip.add:8122 in both HA and HE API maker app but still the devices do not update in HA. Can someone please help me with this?

**Comment by jason0x43** [comment]
On the Home Assistant side, there are two fields to consider: "Event server URL" and "Event server port".

<img width="582" alt="Screenshot 2024-11-02 at 20 06 20" src="https://github.com/user-attachments/assets/25d972cd-4a99-45c5-a5a3-38deb5aa6e41">

"Event server URL" is the URL that the Maker API in Hubitat will be configured to send events to. This address must be accessible by Hubitat on your local network, so it can't involve "localhost" or an internal docker IP address.

"Event server port" is the port on your Home Assistant system that the event server will listen on. This does not have to be the same as the port in the event server URL. For example, you might configure the event server to listen on port 8080, but map 8080->23456 in a Docker compose file, so the event server URL would be `http://host:23456`.

**Comment by jason0x43** [comment]
Closing this since there hasn't been any activity in a while
