### ISSUE TITLE
Device does not work if entity id is changed

### ISSUE THREAD

**Issue by trehan86** [jason0x43/hacs-hubitat#298]
Hi,

I am not sure if someone else is experiencing this but when I bring any device to HA from Hubitat, if I change the Entity Id, the device stops working in HA. I then have to delete the device in HA and add to HA again to make it work. However, the Entity ID cannot be change else the device will stop working again.

**Comment by jason0x43** [comment]
What do you mean by the device stops working? Does the device stop responding to commands from HA, or does the device in HA stop updating to show the real device state?

**Comment by jason0x43** [comment]
Hmm... How are you changing the entity ID, and how are you trying to operate the device? I just tried this locally, by renaming the control entity for a virtual fan from `fan.virtual_fan` to `fan.virtual_fantastic`. After renaming the entity, the fan speed control still works, and the entity maintains its new ID and continues to function after restarting HA.

![2024-11-26 22 02 50](https://github.com/user-attachments/assets/0580b869-b56e-4ea0-80f4-afb26e2df3b4)

Is the problem only occurring after you update the entity name, or do Hubitat devices simply stop updating in HA shortly after HA starts up?

Try enabling [debug logging](https://github.com/jason0x43/hacs-hubitat/tree/v0.9.38-pre0?tab=readme-ov-file#logging) and see if any errors are reported when you update the entity's ID, or when you try to control the entity after updating its ID.

**Comment by trehan86** [comment]
I tried again and seems like the switch works fine even when I change the entity id. The issue seems to be with sensors only. I tried with contact sensor as well as motion sensor and device stops to update status in HA when I change the entity ID. 

![ezgif-7-d42451d6d3](https://github.com/user-attachments/assets/13460067-35bc-4b6e-a43e-bba594738390)

I found below issue in the log. I created a new sensor to make sure that the entity is unique and new for the first time. However, it gives me below error saying that new entity is already in use. I tried
1. removed device from HA and API maker
2. changed name in hubitat
3. added again to HA
4. change the entity ID and below error shows for the new device when I change the entity ID.

2024-11-27 23:35:47.626 WARNING (Recorder) [homeassistant.components.recorder.entity_registry] Cannot migrate history for entity_id `binary_sensor.aa_contact_sensor_contact` to `binary_sensor.aa_contact` because the new entity_id is already in use

The above cannot be correct because I have tried changing entity ID to something I know for sure has never been used before. Also, the changing the entity ID back to the original entity ID does not fix the device. The only way to fix the device again is to completely remove from HA and Maker API and then add again.

**Comment by trehan86** [comment]
An update. I changed the entity id and it stop working for a motion sensor but I left it as is over night. Seems like the sensor is working fine now next day with the new entity id.  

My HA must be doing something that I don’t know how to manage and fix but there is nothing wrong with the integration. Sorry for inconvenience.

**Comment by jason0x43** [comment]
Closing this since the issue seems to be resolved
