### ISSUE TITLE
Hubitat scene appears as On/Off toggle instead of push button

### ISSUE THREAD

**Issue by kerrylarson** [jason0x43/hacs-hubitat#302]
I would like to use a Button on a dashboard to activate a scene on Hubitat.  In my example, the scene or activator 'device' is coming from Hubitat's Maker API to HASS' Hubitat Integration as an On/Off toggle switch.  So once it's ON, I can't turn it ON again without turning it OFF.  I'd like it to be a 'button' where the scene is activated each time the button is pressed.  In Hubitat, the 'device' has On and Off options, but also a 'Push" option, but that doesn't seem to get transferred over to HASS.

What am I misunderstanding?  How do I use a dashboard button to activate a Hubitat scene?  Thanks.

Core 2024.11.3
Supervisor 2024.11.4
Hubitat integration 0.9.38

**Comment by jason0x43** [comment]
The button on the scene is an [event emitter](https://github.com/jason0x43/hacs-hubitat?tab=readme-ov-file#event-emitting-devices), and so it doesn't get a stateful entity. You can use the push button as a device trigger in an automation.

<img width="450" alt="Screenshot 2024-12-01 at 17 37 25" src="https://github.com/user-attachments/assets/97177070-e489-4150-b0f5-c34541952e25">

**Comment by jason0x43** [comment]
I'm closing this, but re-open it if that doesn't work for some reason.

**Comment by kerrylarson** [comment]
I think I'm clueless.  I used a button card on a dashboard as such:
![image](https://github.com/user-attachments/assets/d9a9a3c1-29fa-48da-ba6a-c25c919109f2)
When I click on the Device Info then Automations, I see:
![image](https://github.com/user-attachments/assets/bede8d7d-3010-44b2-8c5f-7d3f9b37a092)
However, when I press the dashboard button,
![image](https://github.com/user-attachments/assets/3c58358f-8b3f-4caa-8a5f-fd5a610eb705)
I just get an info box that pops up:
![image](https://github.com/user-attachments/assets/c23ba073-2273-4c11-afc0-a8756db2e80e)
