### ISSUE TITLE
GIT Error when adding to HASS

### ISSUE THREAD

**Issue by sajid2310** [jason0x43/hacs-hubitat#34]
Exception: HacsException
Message: GitHub returned 404 for https://api.github.com/repos/jason0x43/hacs-hubitat.git
Could not add this repository, make sure it is compliant with HACS.

**Comment by jason0x43** [comment]
Try adding the repo as `jason0x43/hacs-hubitat', not as a fully GitHub URL. Assuming that works, I need to update the README,.

**Comment by sajid2310** [comment]
IT WORKS NOW!!!- 
I am NOOB to Home Assistant (but have HE). Here is the learning I had to do....
1. After installing HASS (VM on Synology NAS) I had to figure out how to install HACS....ie Install SAMBA on HASS. Map Network Drive and select config folder. Create a folder call custom custom_components under config. Copy HACS folder from my local machine...Validate the config (you need to enable this on HASS). Restart HASS
2. After Installing HACS followed your instructions and then added `jason0x43/hacs-hubitat' without quotes and added all other parameters from HE and it works now...

Thanks a ton for the revert and the work you have done

**Comment by sajid2310** [comment]
One Followup question if you make code changes do those reflect automatically or do you  need to remove this from HACS and update again

**Comment by jason0x43** [comment]
HACS will show you when an update is available, and you can update through HACS.

**Comment by jason0x43** [comment]
Closing this since it seems like it's resolved. I updated the README in 07f429e with the proper format to use for the repo when installing the integration.
