### ISSUE TITLE
Feature request - integration with Hubitat Safety Monitor app

### ISSUE THREAD

**Issue by the1poet** [jason0x43/hacs-hubitat#35]
I would like to access the Hubitat Safety monitor controls from Home Assistant.
Is it possible to be able to control arm/disarm, alarm status, cancel alarms, and Home Assistant notification for when it's triggered?

**Comment by jason0x43** [comment]
Hubitat doesn't provide an API (that I'm aware of) for directly interacting with the Hubitat Safety Monitor. HSM emits [location events](https://community.hubitat.com/t/hubitat-safety-monitor-api/934/3) that the integration could listen for to detect state changes. To actually change settings, we'd either need a custom device, or you'd need to setup some virtual switches/buttons that could be exposed through the maker API.

Probably the cleanest solution in the long run would be to make a simple custom HSM device that could be exposed through the Maker API.

**Comment by jason0x43** [comment]
Ah, it seems that the Maker API does have support for HSM. That makes life easier.

**Comment by jason0x43** [comment]
This functionality should probably be presented as an alarm control panel in HA.

**Comment by jason0x43** [comment]
See https://community.hubitat.com/t/announcing-rule-machine-3-0-hub-update-2-0-9-is-available/14758 for HSM API

**Comment by the1poet** [comment]
Hey I did manage to use the events node in the latest version and pass that info to home assistant for the status of the alarm, as well as using virtual buttons and the status node + filters to trigger alarm modes.

**Comment by jason0x43** [comment]
Reopening this because I'd still like to support it.

**Comment by 2exclusive** [comment]
> Reopening this because I'd still like to support it.

Hey was this ever added ? support of HSM vía home assistant ?  Well appreciated if possible thanks

**Comment by jason0x43** [comment]
It hasn't yet, but I still plan to get to it.

**Comment by 2exclusive** [comment]
> It hasn't yet, but I still plan to get to it.

Awesome, I’ll test it as soon as you get it implemented. Thanks again in advance for you working on this!

**Comment by 2exclusive** [comment]
> It hasn't yet, but I still plan to get to it.

Looks like Hubitat added the ability for HSM modes in their maker API on the latest update. Is this now easier to integrate for home assistant?

**Comment by jason0x43** [comment]
It's partway there. The Maker API has had support for modes for a while (though not well documented), and I actually added support for HSM and modes to the support library a [few weeks ago](https://github.com/jason0x43/hubitatmaker/commit/ab3695a029f74ff9844087c8730c1dfc9272b636), but I haven't had a chance to do anything with it in the integration yet. I'll have some free time next week, though. 😄

**Comment by 2exclusive** [comment]
> It's partway there. The Maker API has had support for modes for a while (though not well documented), and I actually added support for HSM and modes to the support library a [few weeks ago](https://github.com/jason0x43/hubitatmaker/commit/ab3695a029f74ff9844087c8730c1dfc9272b636), but I haven't had a chance to do anything with it in the integration yet. I'll have some free time next week, though. 😄

Awesome , many thanks!

**Comment by joehuntley** [comment]
Is this still a planned feature?

**Comment by jason0x43** [comment]
Yes. It's partway implemented, in that the support library supports HSM, I just haven't had time yet to add the corresponding functionality to this integration.

**Comment by dsh1705** [comment]
+1 for this feature!

**Comment by Sandemonium** [comment]
Another +1, but also thank you not only this feature, but the integration as a whole.  I initially set up my HA box as an experiment to see if I could get some additional integration that my hubitat doesn't provide.  I didn't know about HACS or this integration, so I didn't expect it to replace the clunky hubitat app or web GUI and become my go-to for everything.  I'd love to assist, but I'm still a bit of a novice with HA, so I offer my encouragement and if you have a preferred payment/donation method, I'm willing to offer a modest contribution to incentivize this project.

**Comment by syst3x** [comment]
I'm eager to have this feature as well. I've completely switched to HA for my dashboards and HSM status/interaction is the last piece I'm missing. I'm also happy to throw some money in the pot.
