### ISSUE TITLE
Feature Request - Event Type

### ISSUE THREAD

**Issue by mbaran5** [jason0x43/hacs-hubitat#36]
It appears that the 2.2.0 platform update for Hubitat now exposes Physical vs Digital presses for events to MakerAPI. For automation purposes it would be cool to see this added in for further fine tuning. 

> Maker API: Add evt.type for events (physical/digital)

**Comment by jason0x43** [comment]
I added support for this, but I haven't yet seen any events that include a `type` value other than `None`.
