### ISSUE TITLE
inovelli dimmer status doesn't update

### ISSUE THREAD

**Issue by rhd** [jason0x43/hacs-hubitat#4]
Hi again. I've just added an Inovelli dimmer switch to hubitat and shared it with HA.

With a manually fixed POST setting from #1 - I can turn on/off the zooz plug, but it does not work with the inovelli dimmer.

Here is the log from HA

```
2020-02-08 13:32:00 DEBUG (MainThread) [custom_components.hubitat.light] Turning on Living Room Rear Door Light Switch with {}
2020-02-08 13:32:00 INFO (MainThread) [custom_components.hubitat.device] Sent on to 71
2020-02-08 13:32:01 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 192.168.2.125::65
2020-02-08 13:32:01 DEBUG (MainThread) [custom_components.hubitat] received event from <Hub host=192.168.2.125 app_id=65>
```

Here is the log from Hubitat (2 presses)

```
dev:712020-02-08 01:32:38.663 pm infoLiving Room Rear Door Light Switch is on [digital]
dev:712020-02-08 01:32:29.474 pm infoLiving Room Rear Door Light Switch is on [digital]
```

Thoughts?

**Comment by rhd** [comment]
One more difference is that the switch doesn't turn on.. It stays off so HA is technically correct.

I can turn it on from hubitat though.

**Comment by rhd** [comment]
I'm going to close this. It must have been related to #3. I included the zwave device, played with it in hubitat (left it in the on position)... Tried HA saw that it wasn't working at all, then I fixed the post url again.. Then I saw this behavior and created the issue.

Thanks for this integration! Looking forward to the updates.

**Comment by jason0x43** [comment]
Just to check, have you updated to v0.3.0 of the integration, and if so, are you still seeing this problem?

**Comment by rhd** [comment]
I did pull `v0.3.0` and all seems well - great work! Thanks. I verified the POST URL is now consistent and correct too. :+1:

**Comment by jason0x43** [comment]
Great!
