### ISSUE TITLE
Support Hubitat modes

### ISSUE THREAD

**Issue by jason0x43** [jason0x43/hacs-hubitat#42]
Hubitat's mode can be [queried and set](https://community.hubitat.com/t/announcing-rule-machine-3-0-hub-update-2-0-9-is-available/14758) through the Maker API. This should be available through HA.

I'm not aware of an appropriate pre-existing device type in HA. Possibly the mode could be presented via a sensor, and a service could be used to set the mode.

**Comment by jason0x43** [comment]
A received event looks like:

```json
{
  "name": "mode",
  "value": "Morning",
  "displayName": "Home",
  "deviceId": null,
  "descriptionText": "Home is now in Morning mode",
  "unit": null,
  "type": "LOCATION_MODE_CHANGE",
  "data": null
}
```

**Comment by jason0x43** [comment]
* `/modes` gets all modes
* `/modes/:id` sets the mode based on its ID

**Comment by MRobi1** [comment]
> I'm not aware of an appropriate pre-existing device type in HA. Possibly the mode could be presented via a sensor, and a service could be used to set the mode.

Just a thought, could the mode and hsm status be put into an input-select ? For mode it would give it the same look and feel as HE. Making selection from the drop down could then send a mode change request.

**Comment by jason0x43** [comment]
It does seem like it fits the operational model pretty well.

Hmmm...there's an example of dynamically adding an inputs_select at startup in `components/demo/__init__.py`. The integration could do something similar in alarm_control_panel for HSM, and maybe just in the base integration `__init__` for modes. I'll have to experiment a bit there.

**Comment by 2exclusive** [comment]
hubitat just came out with an update 2.2.4.141 which added support to change HSM modes via maker api. would this make it easier to integrate with home assistant ? 

https://community.hubitat.com/t/release-2-2-4-available/55786
