### ISSUE TITLE
In v0.5.1, restarting home assistant re-adds all entities

### ISSUE THREAD

**Issue by the1poet** [jason0x43/hacs-hubitat#45]
Hi,
Every time I restart home assistant on v0.5.1, all my entities from Hubiutat are duplicated with _2 at the end, and all the previous entities are not longer valid.
I have to manually remove the invalid entities and rename them so they reappear in home assistant views.
If I reboot home assistat, it happens again.
I've rolled back to v0.5, and the issue has gone away.

**Comment by jason0x43** [comment]
Hmmm... A big change in 0.5.0 is that the format of entity unique IDs was changed. The entity runs some migration code at startup to update any existing Hubitat entities in HA to use the new format. The issue you're seeing implies that the entity migration isn't being run in 0.5.1, but is in 0.5.0, which shouldn't be the case.

If you [enable debug logging](https://github.com/jason0x43/hacs-hubitat#debugging) for the integration, do you see any messages in the log about migration?

**Comment by jason0x43** [comment]
This was probably resolved by 7b2daf6, in v0.5.4. If it wasn't, we can reopen.
