### ISSUE TITLE
0.110 update Entity name change

### ISSUE THREAD

**Issue by djashjones** [jason0x43/hacs-hubitat#48]
If you upgrade then the integration will break due to this:

https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/

**Comment by jason0x43** [comment]
Those names have been deprecated, but not removed yet. The integration works fine with 0.110.0 and 0.110.1. I should have an update out in a day or two that will use the new classes (if available).

**Comment by jason0x43** [comment]
Actually...let's just keep this open as a reminder. 😁

**Comment by djashjones** [comment]
Sounds good to me 😄
