### ISSUE TITLE
Can't Add Repository

### ISSUE THREAD

**Issue by veilofsecurity** [jason0x43/hacs-hubitat#60]
When adding the repository in the latest version of HomeAssistant the full GitHub URL is required. Adding the repository works once you do that but then you get an error attempting to read the repository:

`20-08-12 21:12:00 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/61db6b2b/repository.json: [Errno 2] No such file or directory: '/data/addons/git/61db6b2b/repository.json'`
`20-08-12 21:12:00 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/61db6b2b/repository.json
`

Per [this issue](https://github.com/home-assistant/supervisor/issues/909), it looks like the repository needs an updated repository.json.

**Comment by jason0x43** [comment]
This is an integration rather than a Home Assistant add-on. To [install it](https://github.com/jason0x43/hacs-hubitat#installation) you’ll need to use HACS or manually install the files.

**Comment by veilofsecurity** [comment]
Oh...derp, thanks.
