### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jason0x43** [jason0x43/hacs-hubitat#61]
The installation instructions have lagged quite a bit behind HACS's current UI. Update them.

**Comment by jason0x43** [comment]
I have a [PR](https://github.com/hacs/default/pull/594) open to get this repo added to HACS's default repo set. That will simplify the instructions since users won't need to manually add the repo.

Another thing to to mention in the docs -- how to use events (`hubitat_event`).

**Comment by jason0x43** [comment]
The HACS install instructions have been updated.

**Comment by boriken72** [comment]
I installed per instructions but Hubitat is not under Configuration --> Integrations --> +

**Comment by jason0x43** [comment]
Did you restart HA after installing the Hubitat integration through HACS?

**Comment by boriken72** [comment]
I had to go to previous version in order for it to show up. The latest
version did not work at all and I installed and u installed various times,
restarted and rebooted several times.

Juan

**Comment by jason0x43** [comment]
The latest version of the Hubitat extension didn't work?

**Comment by boriken72** [comment]
No I’m running 0.5.9 – 0.5.10 did not show up under integrations:

 



 

Installed 0.5.9 and it showed up immediately.

 

--Juan

**Comment by boriken72** [comment]
Also the statuses are incorrect between the two solutions.  This is home assistant showing it’s unlocked:

 



 

Vs 

 

Hubitat (correct state)

**Comment by jason0x43** [comment]
The original issue is resolved in 0a6f4ea. Please open a new issue if you're still having issues installing the integration.
