### ISSUE TITLE
Removing Device on Hubitat leaves behind associated devices and entities in Home Assistant

### ISSUE THREAD

**Issue by Leko1933** [jason0x43/hacs-hubitat#75]
The title kinda says it all, if you remove a device from Hubitat the associated devices and entities stay in Home Assistant and there doesn't seem to be a way to delete them. 

I apologize if I'm missing something obvious or doing something wrong, still very new. So far the only way I've figured out how to fix it is removing the integration on Home Assistant and then re-establishing it, which of course messes up anything you had interacting with devices through the integration. 

Thanks!

**Comment by jason0x43** [comment]
That is expected behavior (that removing a device in Hubitat doesn't remove it in HA).

You should be able to delete invalid entities by browsing to the Entities list in HA, clicking an entity, and clicking the "DELETE" link in the lower left of the dialog that pops up.

**Comment by Leko1933** [comment]
I swear I checked before and the delete button was greyed out but I just checked and it did let me remove it, however the device is still hanging around any thoughts?

Thank you!

**Comment by jason0x43** [comment]
Unfortunately the only way to remove devices currently is to edit the device registry (`config/.storage/core.device_registry`) and manually remove the devices in question. This would be a useful feature, though -- I opened #76 for that.

**Comment by justindthomas** [comment]
Is there any reason this would still be a problem? I'm moving things from Hubitat to Home Assistant and have to remove the entry manually from `core.device_registry` every time - the Delete button is greyed out. This is on a brand new installation of Home Assistant, HACS, and the Hubitat integration (just installed last week).
