### ISSUE TITLE
HTTPS support? 

### ISSUE THREAD

**Issue by jacobwtyler** [jason0x43/hacs-hubitat#84]
Hi I’m new to HA and I’m wanting to port a few HE devices over. It looks like everything is set up okay but I set up HTTPS to make the ST integration work so I can no longer access my HA hub via a local IP. On the HE App side, it asks for an IP to send a post to and I don’t know it it’ll pick up my https://my name.duckdns.org address that I have to use. If so, should I include a :port at the end? Right now it has :39465 at the end. Should I change it to :443 or forward any ports? Thanks.

**Comment by jason0x43** [comment]
The integration starts its own HTTP server on the HA system for Hubitat to post events to, and it configures the maker API on Hubitat with the address and port number of that server. So, as long as HA and Hubitat are on the same network, you should be good.

The integration's server is not the same as HA's own API or UI endpoints. Even if you can only log into your HA instance via HTTPS, this integration's server will still be HTTP.

**Comment by jason0x43** [comment]
Closing this as a dup of #79
