### ISSUE TITLE
User input malformed

### ISSUE THREAD

**Issue by Benz01877** [jason0x43/hacs-hubitat#86]
I´m following the guide to the letter, but when i get to get part Setup i get problems.
Configuration -> Integrations - and searching for Hubitat this window comes up. 
Insert my ip , makers API app ID and access token.
A red text with: User input malformed : shows in the top of the window.
[https://community-assets.home-assistant.io/original/3X/7/b/7bf35594a43651cbea7f1782a72921b38fbd3fc9.png](url)

**Comment by jason0x43** [comment]
This is fixed in v0.5.15.
