### ISSUE TITLE
Lock devices not reporting all state values

### ISSUE THREAD

**Issue by Sab66** [jason0x43/hacs-hubitat#89]
Would love to have lock support added.  Looking to be able to get lastCodeName into HA

**Comment by jason0x43** [comment]
The integration supports lock devices (but I see that they're not mentioned in the readme). You can trigger actions when particular named codes are used to unlock the lock, and you can also listen for `hubitat_event` events, which will have a format like:

```
{
    "event_type": "hubitat_event",
    "data": {
        "device_id": "1234",
        "device_name": "Virtual Lock",
        "attribute": "code_name",
        "value": "Hubitat",
        "description": "Virtual Lock was unlocked by Hubitat",
        "type": null,
        "hub": "xxxxxxx"
    },
    ...
}
```

**Comment by Sab66** [comment]
I did see the lock in HA, but the values for lastCodeName are populated in Hubitat but not in HA logbook.  Maybe I'm not looking in the correct place

**Comment by Sab66** [comment]
![2020-12-04_14-24-39](https://user-images.githubusercontent.com/48997639/101206051-91622c80-363c-11eb-803e-599029d2b7e7.png)

**Comment by Sab66** [comment]
Thanks for your reply and this fantastic app....

**Comment by jason0x43** [comment]
Ah, I think I see the issue. The integration is using the wrong names for some of the lock attributes.

**Comment by Sab66** [comment]
Looks great.  Thank you!
