### ISSUE TITLE
Request for additional domains and sensor types

### ISSUE THREAD

**Issue by aberg83** [jason0x43/hacs-hubitat#9]
Hoping the following can be added:

lock
cover
presence

**Comment by jason0x43** [comment]
Locks and presence should be easy enough.

Hubitat doesn't have a directly equivalent to cover, but it has `DoorControl`, `GarageDoorControl`, and `WindowShade`. Hopefully that will, err, _cover_ the your use cases. 😁

**Comment by aberg83** [comment]
Yes, GarageDoorControl would be what I'm after ;)

**Comment by mbaran5** [comment]
+1 for lock and garage door control.

**Comment by SPCulhane** [comment]
+1 for lock, presence, and GarageDoorControl please.  WindowShade would come in handy in a couple of months for ;)

**Comment by jason0x43** [comment]
> How hard would it be to add keypad support?

Hmmm... I'll have to see what it would match up with in Home Assistant. How do you normally use that type of device with Hubitat?

**Comment by SPCulhane** [comment]
I have a mqtt bridge setup between Hubitat and HA currently. If I recall, its a "securityKeypad" to Hubitat. Within HA, its added as a mqtt-alarm entity.

Hubitat keeps tabs of the codes and the alarm status. It sends the alarm status to mqtt under the "secuityKeypad" topic.

**Comment by aberg83** [comment]
I agree that keypad support would be nice.

As for lock support, it would be great to pass through the code used as an HA attribute.

**Comment by mbaran5** [comment]
> I agree that keypad support would be nice.
> 
> As for lock support, it would be great to pass through the code used as an HA attribute.

Agreed. That would be awesome for automation.

**Comment by jason0x43** [comment]
I'm closing this in favor of of #17, #18, #19, and #20. I doubt I'll get them all done at once, and it's easier to keep track of them this way. 😄
