### ISSUE TITLE
Allow entity type to be overridden for devices

### ISSUE THREAD

**Issue by jason0x43** [jason0x43/hacs-hubitat#92]
Provide some means of overriding entity types, possibly through the integration options system. The primary use case is to provide a way to manually handle the switch vs light ambiguity, although there are likely other cases when this would be useful.

An initial thought is that a user would open the integration options, which could present a list of all entities, including the type of each entity. The user would be able to select different compatible entity types for each entity. Whenever the integration needs to set the type of an entity, it would consult the integration options data to see if there was an override.

**Comment by edalquist** [comment]
I have a Zooz zwave outlet that, in Hubitat, I named "Lava Lamp" and when it got imported into HA it got marked as a light, not a switch. Is issue related to that confusion?

**Comment by jason0x43** [comment]
It is. The integration doesn't have a good way at the moment to know for sure if a switch is just a general switch or is controlling a light, so it checks the device name for clues (e.g, having "lamp" in the name leads the integration to believe the device is a light rather than just a switch).

**Comment by bmorgenthaler** [comment]
So the Light -> Switch (Aeotec Smart Switch 6) worked correctly, however moving a Switch -> Light (Generic Z-Wave Switch) has the entity disappear completely.  It shows up under Devices but without any control options and it does not appear under Entities.

**Comment by jason0x43** [comment]
Closing this since it's implemented. @bmorgenthaler, I opened #98 for your issue.
