### ISSUE TITLE
Error connecting Hubitat

### ISSUE THREAD

**Issue by mrkonyk** [jason0x43/hacs-hubitat#95]
Noticed that the Maker API Get command is different then yours. Wondering how or if I can fix this?

![image](https://user-images.githubusercontent.com/37961707/103472799-b216c280-4d5f-11eb-852f-ff63ec245063.png)

![image](https://user-images.githubusercontent.com/37961707/103472828-189be080-4d60-11eb-8427-4c59474f6ce6.png)

**Comment by iammoen** [comment]
What version of the integration are you on? I am on v0.5.16 and appears to be working the way intended? Although once I enable the integration it doesn't appear that I can go back and enter the app id or the access token again.

**Comment by mrkonyk** [comment]
I'm on version v0.5.16 as well. Sorry I'm new to Home Assistant and having a bit of a hard time wrapping my head around this.

**Comment by iammoen** [comment]
> I'm on version v0.5.16 as well. Sorry I'm new to Home Assistant and having a bit of a hard time wrapping my head around this.

Totally understand. I am new as of 3 days ago myself. Can you describe your setup a little? Is your Ha install on a vm? Or in docker?

**Comment by mrkonyk** [comment]
Thank you for your help :) I'm running Hassio Supervised on Docker (v19.03.12) with HACS (v1.9.0) which I've used to install Hubitat integration. Yes, I've tried http to no avail., still getting a 404 error. Could it have something to do with Docker?

**Comment by jason0x43** [comment]
Are HA and Hubitat on the same network? Like, from the HA machine can you access your Hubitat address?

**Comment by jason0x43** [comment]
Also, it looks like the app ID may have been entered as 963, but from the screenshot in the original post it should have been 20. The easiest way to fix that is to remove the existing instance of the integration and add it again. 

Just go to the Hubitat integration in HA -> Config -> Integrations, click the 3-dot icon in the corner, and choose delete. Then add the integration again.

**Comment by mrkonyk** [comment]
Yep, their both on the same network and docker can see hubitat. See how in this example below the 20 is not the app ID I can't figure out why or what that number is. That example is a Maker API template in Hubitat.

![image](https://user-images.githubusercontent.com/37961707/103487884-8a167600-4dd6-11eb-8cb4-78060a7a3e5d.png)

**Comment by jason0x43** [comment]
If that's the template from the Maker API page in Hubitat, then 20 is the app ID. You can also tell from the URL when you open the Maker API app in Hubitat. For example, my template on the Maker API page looks like this:

<img width="546" alt="Screen Shot 2021-01-03 at 8 55 26 PM" src="https://user-images.githubusercontent.com/1042866/103494832-7551d680-4e06-11eb-8d5e-d96655db9f7b.png">

and the URL of that page is `http://10.0.1.199/installedapp/configure/1/mainPage`

**Comment by mrkonyk** [comment]
You were absolutely right! Thank you very much for your help..

**Comment by jason0x43** [comment]
Closing this since the issue seems to be resolved.
