### ISSUE TITLE
Support dimmer switches

### ISSUE THREAD

**Issue by iammoen** [jason0x43/hacs-hubitat#96]
There doesn't seem to dimmer switch support? If that is accurate I might try my hand at making a PR for it. If there is maybe I am just not looking in the right place.

**Comment by jason0x43** [comment]
Dimmable switches will be added as light entities in HA by default.

**Comment by iammoen** [comment]
> Dimmable switches will be added as light entities in HA by default.

Ah. So I need to change that in HA.

**Comment by jason0x43** [comment]
Yeah, HA doesn't have the concept of a "dimmable switch". Switches with level support map to more specific types, like lights, fans, or covers.

**Comment by jason0x43** [comment]
Closing this since dimmers are supported. Getting them to appear as a different type would be handled in #92.
