### ISSUE TITLE
Switch -> Light override loses entity

### ISSUE THREAD

**Issue by jason0x43** [jason0x43/hacs-hubitat#98]
In v0.6.0, overriding a light to a switch works, but overriding the other way may leave a device with no usable entities.

See [this comment](https://github.com/jason0x43/hacs-hubitat/issues/92#issuecomment-754751588)

**Comment by bmorgenthaler** [comment]
@jason0x43 What information can I gather for you?

**Comment by jason0x43** [comment]
I'm pretty sure I know what's wrong. The logic in the light handler that's used to figure out if a device is a light or a switch is running even when an override is present. Silly mistake on my part. 😄  I should have a fix out tonight.
