### ISSUE TITLE
Hubitat Stopped Sending Update to Home Assistant

### ISSUE THREAD

**Issue by gcortes** [jason0x43/hacs-hubitat#99]
I've had Hubitat and Home Assistant communicating for a couple of days now. I've been adding devices to HE that I moved from SmartThings. Sometime today, HE stopped sending notifications to HA. For example, I have a motion sensor under my desk. If I move my foot, I see the status change on the HE dashboard, but not in HA. I checked the log and didn't see any errors. I rebooted both HA and HE and did a reload in Integrations. I also cleared the cache. Is there anywhere else I can look for error messages. The only other different thing I did today was turn off my SmartThings hub since I've moved everything off of it. I tried turning it back on to see if it would make any difference. Unsurprisingly, it didn't. The last thing I added to HE was a Schlage Lock. That was earlier today. I just now clicked on unlock in HA and it worked although it didn't change the status in HA. It did in HE. Pressing Lock afterward doesn't work. HA is running on Docker on Ubuntu. It's connected to the same switch and the HE hub.

**Comment by jason0x43** [comment]
The easiest check is to see what the event POST URL is in the Maker API instance in HE. That's where HE sends all its updates, so if that's not correct, HA isn't going to see anything.

The next step would be to enable debug logging for the integration and restart HA. Check the log for any hubitat-related issues during startup. Verify that the integration is setting the event server URL to the proper value (there will be a log message mentioning that). Try triggering a sensor in HE. If everything is communicating properly, multiple messages should show up in the HA log for received events.

**Comment by gcortes** [comment]
@jason0x43, I'll do those checks later this morning. One other thing I did yesterday that I just remembered was upgrading Hubitat in HACS. Your app is the only Hubitat one that I've installed.

**Comment by gcortes** [comment]
@jason0x43, I fixed it by going to integrations, hubitat options, clicking submit, and continued through the dialog panels without making any changes.

**Comment by jason0x43** [comment]
Hmmm...were you overriding the event server port or URL before upgrading? Something may have changed in how the stored config options are handled, and running through the options flow rebuilds the stored options.

**Comment by jason0x43** [comment]
Interesting. Well, I'm going to close this since the issue appears to have self resolved, but we can definitely revisit if the issue recurs.
